name: CD
on:
  push:
    tags:
      - v*.*.*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/
      - run: npm set -g //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: npm install --no-fund --no-shrinkwrap --no-package-lock --no-audit
      - run: npm run build
      - run: npm run test
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
